baseurl = "http://www.harth-lang.org/"
languageCode = "en-us"
title = "Harth Programming Language"
disqusShortname = "610yesnolovely" # Optional, enable Disqus integration
MetaDataFormat = "yaml"
theme = "hugo-read-the-docs"
paginate = 10

[author]
    name = "Harth Software"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]


