baseurl = "http://www.harth-lang.org/"
languageCode = "en-us"
title = "Harth Programming Language"
disqusShortname = "610yesnolovely" # Optional, enable Disqus integration
MetaDataFormat = "yaml"
theme = "harth-hugo-theme"
paginate = 10

[author]
    name = "Harth Software"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]


# Menu configuration should come last in this file;
# leave at least one blank line at the end
#

#
# Blog
#
[[menu.main]]
  name = "Blog"
  identifier = "mn_blog"
  weight = 1

#
# Component projects is a menu for Registry/Notary etc.
#
[[menu.main]]
  name = "Component Projects"
  identifier = "mn_components"
  weight = 8

#
# Component projects is a menu for Registry/Notary etc.
#
[[menu.main]]
  name = "API reference"
  parent = "mn_components"
  weight = 90

#
# About
#
[[menu.main]]
  name = "About"
  identifier = "mn_about"
  weight = 9

#
# Version
#
[[menu.main]]
  name = "Docs archive"
  identifier = "mn_versions"
  weight = 10

[[menu.main]]
  name = "Version 1.9"
  identifier = "smn_nineteen"
  parent = "mn_versions"
  url = "http://docs.docker.com/v1.9/"
  weight = -1

[[menu.main]]
  name = "Version 1.8"
  identifier = "smn_eightteen"
  parent = "mn_versions"
  url = "http://docs.docker.com/v1.8/"
  weight = 1
