baseurl = "http://www.harth-lang.org/"
languageCode = "en-us"
title = "Harth Programming Language"
# disqusShortname = "610yesnolovely" # Optional, enable Disqus integration
MetaDataFormat = "yaml"
theme = "harth-hugo-theme"
paginate = 10

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

[params]
    description = "Harth Programming Language"
    author = "Harvey Thompson"
    generator = "Hugo 0.15"
    title = "XXX"

