baseurl = "http://www.harth-lang.org/"
languageCode = "en-us"
title = "Harth Programming Language"
author = ["Harvey Thompson"]
disqusShortname = "610yesnolovely"
MetaDataFormat = "yaml"
theme = "harth-hugo-theme"
paginate = 10
pygmentsCodeFences = true

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

[params]
    title_html = "Harth<br>Programming<br>Language"
    description = "Harth Programming Language"
    author = "Harvey Thompson"
    generator = "Hugo 0.15"

[[menu.main]]
  name = "Home"
  identifier = "mn_home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Language Reference"
  identifier = "mn_ref"
  url = "/ref/"
  weight = 2

[[menu.main]]
  name = "Language API"
  identifier = "mn_api"
  url = "/api/"
  weight = 3

[[menu.main]]
  name = "Blog"
  identifier = "mn_blog"
  url = "/post/"
  weight = 4

[[menu.main]]
  name = "License"
  url = "/license/"
  weight = 5
